---
title: "Untitled"
author: "Aaron Owen"
date: "10/19/2017"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
profs = read.csv("profs.csv", stringsAsFactors = F)
profs = profs %>% select(-X, -X.1)
```

```{r}
head(profs)
```

```{r}
profs$department[grepl("Biological", profs$department)] = "Biology"
profs$department[grepl("Business Te", profs$department)] = "Business"
profs[profs$department == "Science", ]$department = "Physical Sciences"
profs$department[grepl("Theater|Speech", profs$department)] = "Communication"
profs[profs$name == "Greco, Joseph", ]$department = "Communication"
profs[profs$name == "Sokolski, Patricia", ]$department = "Communication"
profs$department[grepl("Allied", profs$department)] = "Health Science"
profs$department[grepl("Health & Physical Education|Physical Education", profs$department)] = "Physical Ed"
profs$department[grepl("Art", profs$department)] = "Art"
profs$department[grepl("Legal", profs$department)] = "Law"
profs$department[grepl("African|Ethnic|Women", profs$department)] = "Cultural Studies"
profs$department[grepl("Foreign|Spanish", profs$department)] = "Languages"
profs$department[grepl("Info", profs$department)] = "Social Science"
profs[profs$name == "Townsend, Charles", ]$department = "Social Science"
profs[profs$name == "Ruiz, Roberto", ]$department = "Philosophy"
profs$department[grepl("History|Political|Philosophy", profs$department)] = "History, Philosophy, Poly Sci"
profs = profs %>% mutate(chili = ifelse(grepl("True", chili), "attractive", "not attractive"))
```

```{r}
profs["total_tags"] = apply(profs[10:29], 1, sum, na.rm = T)
profs[profs$school == "qns", ]$school = "QNS"
profs[profs$school == "king", ]$school = "KNG"
profs[profs$school == "nas", ]$school = "NAS"
profs[profs$school == "lg", ]$school = "LAG"
profs[profs$school == "man", ]$school = "MAN"

```

```{r}
grouped_profs = 
    profs %>% group_by(name, school, sex, department) %>%
        summarise_if(is.numeric, mean, na.rm = T) %>% 
        mutate(
           `Accessible Outside of Class` = accessible.outside.class/total_tags * 100,
           `Amazing Lectures` = amazing.lectures/total_tags * 100,
           `Beware of Pop Quizzes` = beware.of.pop.quizzes/total_tags * 100,
           Caring = caring/total_tags * 100,
           `Clear Grading Criteria` = clear.grading.criteria/total_tags * 100,
           `Extra Credit` = extra.credit/total_tags * 100,
           `Get Ready to Read` = get.ready.to.read/total_tags * 100,
           `Gives Good Feedback` = gives.good.feedback/total_tags * 100,
           `Graded by Few Things` = graded.by.few.things/total_tags * 100,
           `Group Projects` = group.projects/total_tags * 100,
           Hilarious = hilarious/total_tags * 100,
           Inspirational = inspirational/total_tags * 100,
           `Lecture Heavy` = lecture.heavy/total_tags * 100,
           `Lots of Homework` = lots.of.homework/total_tags * 100,
           `Participation Matters` = participation.matters/total_tags * 100,
           Respected = respected/total_tags * 100,
           `Skip Class? You won't Pass` = skip.class.you.wont.pass/total_tags * 100,
           `So Many Papers` = so.many.papers/total_tags * 100,
           `Test Heavy` = test.heavy/total_tags * 100,
           `Tough Grader` = tough.grader/total_tags * 100)
```

```{r}
grouped_profs = grouped_profs %>% rename(overall_score_mean = overall_score, difficulty_score_mean = difficulty_score)
grouped_profs[, -(5:27)]
```

```{r}
profs = merge(profs, grouped_profs[, -(5:27)], by = c("name"), suffixes = c("", "_y")) %>% select(-school_y, -sex_y, -department_y)
profs
write.csv(profs, "profs_cleaned.csv")
```

```{r}
df = profs %>% filter(school == "QNS", department == c("Accounting", "Biology", "Business"))

to_merge = as.data.frame(table(df$overall_score, df$difficulty_score, df$sex))
dummy = data.frame(Var1 = as.factor(rep(c(1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5), 10)), 
                   Var2 = as.factor(rep(1:5, 18)), 
                   Var3 = as.factor(c(rep("female", 45), rep("male", 45))))

all = merge(dummy, to_merge, on = c(Var1, Var2, Var3), all.x = T)

all[is.na(all)] = 0

all$prop = 0

names(all) = c("overall_score", "difficulty_score", "sex", "count", "proportion")

all = all %>% arrange(sex)

all[c(1:45), 5] = round(all[1:45, 4] / sum(all[1:45, 4]) * 100, 1)
all[c(46:90), 5] = round(all[46:90, 4] / sum(all[46:90, 4]) * 100, 1)

ggplot(all, aes(difficulty_score, overall_score, fill = count)) +
    geom_tile() +
    geom_text(aes(label = proportion, color = sex, hjust = ifelse(sex == "female", 1.5, -0.5))) +
    scale_colour_manual("% Sex", values = c("red","green"))






df = profs %>% filter(school == "qns", department == c("Biology", "Art"))
to_merge = as.data.frame(table(df$overall_score, df$difficulty_score, df$sex))

# don't know how many chilis and not chilis there are for each cell in the grid
dummy = data.frame(Var1 = as.factor(rep(c(1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5), 10)), Var2 = as.factor(rep(1:5, 18)))
#, Var3 = as.factor(c(rep("attractive", 45), rep("not attractive", 45))))

all = merge(dummy, to_merge, on = c(Var1, Var2), all = T)

all$Var3 = as.character(all$Var3)

all[is.na(all$Var3), ]$Var3 = "not rated"

all[is.na(all)] = 0

all$prop = 0

names(all) = c("overall_score", "difficulty_score", "pepper", "count", "proportion")

all[c(1:45), 5] = round(all[1:45, 4] / sum(all[1:45, 4]) * 100, 1)
all[c(46:90), 5] = round(all[46:90, 4] / sum(all[46:90, 4]) * 100, 1)

all[all$pepper == "not rated", ]$proportion = "not rated"

ggplot(all, aes(difficulty_score, overall_score, fill = count)) +
    geom_tile() +
    geom_text(aes(label = proportion, color = pepper, 
                  hjust = ifelse(pepper == "not rating", 0.5, ifelse(pepper == "attractive", 1.5, -0.5)))) +
                      #pepper == "attractive", 1.5, ifelse(pepper == "not attractive", -0.5, 0)))) +
    scale_colour_manual("% chili", values = c("red","green", "black"))

```

```{r}
df = profs %>% filter(department == "Physics")
all = as.data.frame(table(df$overall_score, df$difficulty_score, df$sex))

all$prop = 0

all[c(1:45), 5] = round(all[1:45, 4] / sum(all[1:45, 4]) * 100, 1)
all[c(46:90), 5] = round(all[46:90, 4] / sum(all[46:90, 4]) * 100, 1)

ggplot(all, aes(Var2, Var1, fill = Freq)) +
    geom_tile() +
    geom_text(aes(label = prop,colour = Var3, hjust = ifelse(Var3 == "female", 1.5, -0.5))) +
    scale_colour_manual("% Sex", values = c("red","green"))

```

```{r}
ggplot(all, aes(x = Var2, y = Var1)) + geom_tile(aes(fill = Freq)) + 
    annotate("text", x = 0.75, y = 1, label = round(female$Freq[1] / all$Freq[1]  * 100, 1), color = "red") +
    annotate("text", x = 1.25, y = 1, label = round(male$Freq[1]  / all$Freq[1] * 100, 1), color = "white") +
    annotate("text", x = 0.75, y = 2, label = round(female$Freq[2] / all$Freq[2]  * 100, 1), color = "red") +
    annotate("text", x = 1.25, y = 2, label = round(male$Freq[2]  / all$Freq[2] * 100, 1), color = "white") +
    annotate("text", x = 0.75, y = 3, label = round(female$Freq[3] / all$Freq[3]  * 100, 1), color = "red") +
    annotate("text", x = 1.25, y = 3, label = round(male$Freq[3]  / all$Freq[3] * 100, 1), color = "white") # +
    # annotate("text", x = 0.75, y = 4, label = round(female$Freq[4] / all$Freq[4]  * 100, 1), color = "red") +
    # annotate("text", x = 1.25, y = 4, label = round(male$Freq[4]  / all$Freq[4] * 100, 1), color = "white") +
    # annotate("text", x = 0.75, y = 5, label = round(female$Freq[5] / all$Freq[5]  * 100, 1), color = "red") +
    # annotate("text", x = 1.25, y = 5, label = round(male$Freq[5]  / all$Freq[5] * 100, 1), color = "white") +
    # annotate("text", x = 0.75, y = 6, label = round(female$Freq[6] / all$Freq[6]  * 100, 1), color = "red") +
    # annotate("text", x = 1.25, y = 6, label = round(male$Freq[6]  / all$Freq[6] * 100, 1), color = "white") + 
    # annotate("text", x = 0.75, y = 1, label = round(female$Freq[1] / all$Freq[1]  * 100, 1), color = "red") +
    # annotate("text", x = 1.25, y = 1, label = round(male$Freq[1]  / all$Freq[1] * 100, 1), color = "white") +
    # annotate("text", x = 0.75, y = 2, label = round(female$Freq[2] / all$Freq[2]  * 100, 1), color = "red") +
    # annotate("text", x = 1.25, y = 2, label = round(male$Freq[2]  / all$Freq[2] * 100, 1), color = "white") +
    # annotate("text", x = 0.75, y = 3, label = round(female$Freq[3] / all$Freq[3]  * 100, 1), color = "red") +
    # annotate("text", x = 1.25, y = 3, label = round(male$Freq[3]  / all$Freq[3] * 100, 1), color = "white") +
    # annotate("text", x = 0.75, y = 4, label = round(female$Freq[4] / all$Freq[4]  * 100, 1), color = "red") +
    # annotate("text", x = 1.25, y = 4, label = round(male$Freq[4]  / all$Freq[4] * 100, 1), color = "white") +
    # annotate("text", x = 0.75, y = 5, label = round(female$Freq[5] / all$Freq[5]  * 100, 1), color = "red") +
    # annotate("text", x = 1.25, y = 5, label = round(male$Freq[5]  / all$Freq[5] * 100, 1), color = "white") +
    # annotate("text", x = 0.75, y = 6, label = round(female$Freq[6] / all$Freq[6]  * 100, 1), color = "red") +
    # annotate("text", x = 1.25, y = 6, label = round(male$Freq[6]  / all$Freq[6] * 100, 1), color = "white")

```

```{r}
profs %>% filter(chili == "not attractive") %>%
    ggplot(aes(x = difficulty_score, y = overall_score)) + geom_point(position = "jitter") + 
    geom_smooth(aes(color = sex), method = "lm", se = F)
    #geom_smooth(aes(color = chili), method = "lm", se = F)
    # geom_bar(stat = "identity", position = "stack")

profs %>% filter(sex == "female") %>%
    ggplot(aes(x = difficulty_score, y = overall_score)) + geom_point(position = "jitter") + 
    #geom_smooth(aes(color = sex), method = "lm", se = F) +
    geom_smooth(aes(color = chili), method = "lm", se = F)
    # geom_bar(stat = "identity", position = "stack")

profs %>% 
    group_by(difficulty_score_fac) %>% ggplot(aes(x = difficulty_score_fac, y = overall_score)) + geom_violin()
    summarise(mean_ = mean(overall_score), sd_ = sd(overall_score), count = n()) %>%
    ggplot(aes(x = difficulty_score_fac, y = mean_)) + geom_violin()

x$error_bar = 1.96*(x$sd_/sqrt(x$count))




x

x %>% 
    ggplot(aes(x = difficulty_score_fac, y = mean_)) + geom_violin() +
    # geom_errorbar(aes(ymin = mean_ - error_bar, ymax = mean_ + error_bar), width = 0.25) + 
    # geom_point() + ylim(c(0, 5))


    
 
 geom_bar(stat = "identity", position = "dodge")
    # +
    #geom_smooth(inherit.aes = F, aes(x = difficulty_score, y = abc, color = sex), method = "lm", se = F) #+
    #geom_smooth(inherit.aes = F, aes(x = difficulty_score, y = abc, color = chili), method = "lm")


summary(lm(profs$overall_score ~ profs$difficulty_score))
summary(aov(overall_score ~ difficulty_score * sex, data = profs))

x = profs %>% filter(chili == "not attractive")
summary(aov(overall_score ~ difficulty_score * sex, data = x))

cor.test(profs$overall_score, profs$difficulty_score)
# + geom_smooth(method = "lm")




    stat_sum(inherit.aes = F, aes(x = difficulty_score, y = overall_score, 
                                color = sex, label = paste(round(..prop.. * 100, 1))), 
           size = 4, geom = "text", position = position_dodge(width = 0.8)) + 
    scale_color_manual(values = c("red", "orange")) + 
    theme(panel.background = element_rect(fill = "black"), panel.grid.major = element_blank(),
          panel.grid.minor.y = element_blank()) +
    geom_hline(yintercept = 0.75, color = "white") +
    geom_hline(yintercept = 1.25, color = "white") +
    geom_hline(yintercept = 1.75, color = "white") +
    geom_hline(yintercept = 2.25, color = "white") +
    geom_hline(yintercept = 2.75, color = "white") +
    geom_hline(yintercept = 3.25, color = "white") +
    geom_hline(yintercept = 3.75, color = "white") +
    geom_hline(yintercept = 4.25, color = "white") +
    geom_hline(yintercept = 4.75, color = "white") +
    geom_hline(yintercept = 5.25, color = "white")


```

```{r}
summarySE = function(data = NULL, measurevar, groupvars = NULL, na.rm = FALSE,
                      conf.interval = .95, .drop = TRUE) {
    library(plyr)

    length2 = function (x, na.rm = FALSE) {
        if (na.rm) sum(!is.na(x))
        else length(x)
    }

    datac = ddply(data, groupvars, .drop = .drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm = na.rm),
          mean = mean   (xx[[col]], na.rm = na.rm),
          sd   = sd     (xx[[col]], na.rm = na.rm)
        )
      },
      measurevar
    )
   
    datac = rename(datac, c("mean" = measurevar))

    datac$se = datac$sd / sqrt(datac$N)  

    ciMult = qt(conf.interval/2 + .5, datac$N-1)
    datac$ci = datac$se * ciMult

    return(datac)
}
```

```{r}
z = data.frame(x = 1:10, y = 2:11)
ggplot(z, aes(x = x, y = y)) + geom_point() + for (i in 1:nrow(z)) {
    annotate("text", x = 0.3, y = 3, label = "hi", color = "black")
}

d <- expand.grid(x=1:5,y=1:5)
d$z <- rnorm(nrow(d))
d$label <- sample("23.5", size = nrow(d), replace = TRUE)
d$label2 = sample("99.0", size = nrow(d), replace = TRUE)
d$sex = c("M", "M", "M", "M", "M", "F", "F", "F", "F", "F")

ggplot(d, aes(x,y,fill=z)) + geom_tile() +
    geom_text(aes(label=label, color = sex), nudge_x = 0.2) +
    geom_text(aes(label=label2), nudge_x = -.2) +
    
d <- expand.grid(x=1:5,y=1:5)
d$z <- rnorm(nrow(d))
d$f <- sample("35", size = nrow(d), replace = TRUE)
d$m <- sample("65", size = nrow(d), replace = TRUE)

d
dd <- tidyr::gather(d, gender, label, -x,-y,-z)
dd
ggplot(dd, aes(x,y,fill=z)) + geom_tile() +
  geom_text(aes(label=label,colour=gender, hjust = ifelse(gender=="f", 1.5,-0.5))) +
  scale_colour_manual("gender", values=c("pink","green"))
        
    # annotate("text", x = 0.75, y = 1, label = round(female$Freq[1] / all$Freq[1]  * 100, 1), color = "red")
```

```{r}
abc = profs %>% filter(department == "Chemistry") %>% group_by(school) %>% summarise(overall = mean(overall_score), diff = mean(difficulty_score))
xyz = tidyr::gather(abc,rating, score, -school)
ggplot(xyz, aes(x = school, y = score, fill = rating)) + geom_bar(stat = "identity", position = "dodge")
# ggplot(y, aes(x = Complaint.Type2, y = count, fill = Complaint.Type2)) + geom_bar(stat = "identity") + coord_flip()
```

```{r}
x = grouped_profs[, c(1:4, 28:47)] %>% group_by(school, department) %>% summarise_if(is.numeric, mean, na.rm = T)
x
write.csv(x, "grouped_profs.csv")
grouped_profs


profs

x
class(z)

z = x %>% select(acc.out.class.prop, department, school) %>% 
    filter(department == "Accounting") %>% 
    group_by(school) %>% 
    summarise(abc = mean(acc.out.class.prop, na.rm = T))

z[is.na(z)] = 0

ggplot(z, aes(x = school, y = abc, fill = school)) + geom_bar(stat = "identity")
+ 
    ggplot(aes(x = school, y = abc, fill = school)) + geom_bar(stat = "identity") 

#+ 
    scale_x_discrete(limits = c("king", "lg", "man", "nas", "qns"))

x = tidyr::gather(x, props, values, -school, -department) 

print(x)

x %>% filter(props == "Tough Grader", department == "Biology") %>% 
    ggplot(aes(x = props, y = values, fill = school)) +
    geom_bar(stat = "identity", position = "dodge") #+ scale_x_discrete(limits = c("king", "lg", "man", "nas", "qns"))

# grouped_profs %>% filter(school == "king", department == "Biology") %>% summarise(mean(tough.grader.prop))

paste(strsplit("skp?.are.you", split = "\\.")[[1]], collapse = " ")
```

```{r}
library(tm)
library(wordcloud)
library(memoise)

z = profs %>% filter(department == "Biology") %>% group_by(school) %>% select(school, content)
man_vec = z[z$school == "MAN", ][[2]]
lag_vec = z[z$school == "LAG", ][[2]]
qns_vec = z[z$school == "QNS", ][[2]]
kng_vec = z[z$school == "KNG", ][[2]]
nas_vec = z[z$school == "NAS", ][[2]]

content_vec = profs[profs$department == "Biology", "content"]

my_corp = Corpus(VectorSource(content_vec))
my_corp = tm_map(my_corp, content_transformer(tolower))
my_corp = tm_map(my_corp, removePunctuation)
my_corp = tm_map(my_corp, removeNumbers)
my_corp = tm_map(my_corp, removeWords,
                 c(stopwords("SMART"), "the", "and", "you", "his", "she", "professor", "her", "for", "but",
                   "are", "will", "take", "him", "this", "have", "that", "with", "all", "was", "your", "dont",
                   "prof", "teacher", "hes", "makes", "lot", "make", "doesnt", "shes", "student", "taking",
                   "professors", "youll", "person", "teaches", "ive", "highly", "guy", "youre", "made", "class"))

myDTM = TermDocumentMatrix(my_corp, control = list(minWordLength = 1))

m = as.matrix(myDTM)
v = sort(rowSums(m), decreasing = T)
d = data.frame(word = names(v), freq = v)

# set.seed(1234)
wordcloud(words = d$word, freq = d$freq, scale = c(4, 0.05), min.freq = 10,
          max.words = 100, random.order = F, rot.per = 0.35, colors = brewer.pal(8, "Dark2"))

"hi"
```

```{r}
(profs %>% filter(department == "Chemistry") %>% select("content"))[[1]]
```











